### ISSUE TITLE
Executable bit in library files is no longer removed when building with distutils.core

### ISSUE THREAD

**Issue by befeleme** [pypa/distutils#123]
This issue impacts packages using distutils to build, like [visvis](https://github.com/almarklein/visvis/blob/master/setup.py#L36).
The Python's distutils removes the executable bit from library files, while the version bundled with setuptools 60.9.3 doesn't.
I'd expect for the setuptools' distutils behavior to follow the former logic, i.e. removing the bit. 

Steps to reproduce using visvis repository:
```console
# Behavior till now
$ git@github.com:almarklein/visvis.git
$ pip install -U setuptools
$ export SETUPTOOLS_USE_DISTUTILS=stdlib
$ python setup.py build
$ ls -ll build/lib/visvis/examples/
total 148
-rw-r--r--. 1 root root  870 Mar  4 07:59 anisotropicData.py
-rw-r--r--. 1 root root  914 Mar  4 07:59 anisotropicData2.py
-rw-r--r--. 1 root root 1462 Mar  4 07:59 bouncingBall.py
<snip>

# the same with setuptools' distutils
$ rm -rf build/
$ export SETUPTOOLS_USE_DISTUTILS=local
$ python setup.py build
$ ls -ll build/lib/visvis/examples/
total 148
-rwxr-xr-x. 1 root root  870 Mar  4 07:59 anisotropicData.py
-rwxr-xr-x. 1 root root  914 Mar  4 07:59 anisotropicData2.py
-rwxr-xr-x. 1 root root 1462 Mar  4 07:59 bouncingBall.py
<snip>
```

**Comment by jaraco** [comment]
One thing to note about the setuptools-supplied version is that it also applies all of the Setuptools-specific behaviors, including the [monkey patching of distutils](https://github.com/pypa/setuptools/blob/0ec53b228800300992ba1c53c2f089a435d4970c/setuptools/monkey.py#L63). So the first thing we should bisect is the effect of Setuptools. One way to do that could be to use this copy of distutils without setuptools.

**Comment by jaraco** [comment]
Using pure distutils from this repo, I see the behavior is unchanged from stdlib:

```
draft $ git clone gh://almarklein/visvis
Cloning into 'visvis'...
remote: Enumerating objects: 5362, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 5362 (delta 45), reused 79 (delta 27), pack-reused 5248
Receiving objects: 100% (5362/5362), 6.28 MiB | 8.70 MiB/s, done.
Resolving deltas: 100% (4012/4012), done.
draft $ cd visvis
visvis master $ env PYTHONPATH=/Users/jaraco/p/pypa/distutils python -c "import distutils; print(distutils.__file__)"
/Users/jaraco/p/pypa/distutils/distutils/__init__.py
visvis master $ env PYTHONPATH=/Users/jaraco/p/pypa/distutils python setup.py -q build
/Users/jaraco/p/pypa/distutils/distutils/dist.py:275: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/Users/jaraco/p/pypa/distutils/distutils/dist.py:275: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
visvis master $ ls -l build/lib/visvis/examples/ | head -n 4
total 296
-rw-r--r--  1 jaraco  staff   870 Mar 27 19:58 anisotropicData.py
-rw-r--r--  1 jaraco  staff   914 Mar 27 19:58 anisotropicData2.py
-rw-r--r--  1 jaraco  staff  1462 Mar 27 19:58 bouncingBall.py
```

So it seems to me it's the Setuptools behavior that's implicated.

In this case, I consider the Setuptools behavior to be preferable, as it's more mature and more widely adopted.

If you wish to rely on the legacy behavior, I'd continue to use the SETUPTOOLS_USE_DISTUTILS=stdlib.

If you believe the distutils behavior is something that should be the default behavior for Setuptools, please provide the rationale and I can transfer this issue to that repo and we can consider it there.

By the way, stdlib distutils is deprecated and setuptools' copy of distutils will become deprecated soon too, so please consider simply switching to rely on Setuptools instead of distutils.
