### ISSUE TITLE
Status of mingw64 support

### ISSUE THREAD

**Issue by elandorr** [pypa/distutils#146]
Hi there,

what's the gist of official mingw64 support? I read MSYS2 hacked it together, but I don't have time to figure out how exactly.

Building individual files manually via the 'clean' winlibs.com chain works fine.

Microsoft now forces, literally, forces a gigantic spyware perma-online installer just to get the basic compiler. It is now completely useless and will never disgrace any system I deal with again.

Mingw works great, but integration with distutils is needed to not go mad. I don't know if this is a big change for you guys, or a simple config flip. If it is the latter, please tell.

Thank you

**Comment by jaraco** [comment]
Hi elandorr. I'm the maintainer, but I'm unaware of the status you seek. If it is supported, you'll need to rely on the source or the community for support. I welcome you to explore the space and develop the expertise needed to investigate/implement the necessary support.

I did search through the issues, and it does appear as if there are others interested in MINGW support, but most around 32-bit. Maybe some of those users would have interest in working on this issue.

> Microsoft now forces, literally, forces a gigantic spyware perma-online installer just to get the basic compiler. It is now completely useless and will never disgrace any system I deal with again.

I understand your frustration, but please be aware that the [Python Community Code of Conduct](https://www.python.org/psf/conduct/) asks everyone to be respectful of others, which includes developers at Microsoft who have developed the compiler solutions some of whom might be here and those in the PyPA who have rallied their support behind the official compiler. You of course are not required to accept those approaches, but do please try to avoid using hyperbolic defamatory statements ("literally forces", "completely useless).

**Comment by lazka** [comment]
Yeah, I got sidetracked a bit on that topic.. but we still plan to get vanilla distutils/setuptools working in MSYS2.

**Comment by jaraco** [comment]
> [more gripes about Microsoft]

Perhaps I was unclear. Please refrain from using this forum as a sounding board to gripe about others (companies or whatever). Stick to the topic of what distutils can or can't do for its users. If you wish to vent about other topics, I suggest you take that elsewhere like a blog or reddit. Thanks.

> That's a very odd way of saying 'go hackjob it yourself'.

It's odd because that's not what I'm trying to say. I'm asking those who are invested and interested in a feature to take responsibility for owning the design and implementation. Other options are to create a bounty or negotiate some funding or convince someone else to get it done.

I volunteer my time to ensure that the project is making progress in its key objectives (right now to ensure a transition from distutils in stdlib) and to support community contributions. If you're not capable or willing to learn the software and implement a robust design, then I agree, it may not be worth your time. If on the other hand, you'd like to invest some time and come up with a reasonably sound design, I'll donate my time to critique and refine the solution, roll it out to users, respond to regressions, and maintain the software going forward.
