### ISSUE TITLE
`test/test*.py` vs. `tests/test*.py`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pypa/distutils#187]
While I do not mind the Python Packaging User Guide referring to either `test/` or `tests/` or even a random word as an example of a directory that contains tests, I believe actual code should support `tests/` in addition to `test/`:
https://github.com/pypa/distutils/blob/e0787fad7c03d8defbbaaaf2888130cc2a171537/distutils/command/sdist.py#L295-L296

I think most packages out there use `tests/`.

See https://github.com/pypa/packaging.python.org/issues/1165 and before that https://github.com/codespell-project/codespell/issues/2592#issuecomment-1318245675.

**Comment by jaraco** [comment]
I'm not sure that `test/test*.py` is a good default here. It excludes files that don't start with `test` (i.e. conftest.py) but includes files that do (i.e. tester_notes.py). And as you've pointed out, it only honors a `test` directory and not `tests`. Maybe the default should be `test*/**/*` (everything in any subdirectory of any directory that begins with `test`). Or maybe the default should be removed altogether (making no inference about which files should be included in sdist).

In my projects, I rely on `setuptools_scm` to add _every file under source code management_, so I don't deal with defaults or implicit overrides. I do as a matter of course [exclude tests from packages to install](https://github.com/jaraco/skeleton/blob/9e13598ce4b81c2c964dd555fa407bb3ba4cc607/setup.cfg#L26).

My instinct is to remove the default altogether, except for the backward-compatibility concerns that could raise. We could, through a deprecation process, wean projects off of reliance on this default. Since it has to do with sdist generation, it's probably not something that needs extended backward compatibility (old sdists are unaffected by any change).

**Comment by DimitriPapadopoulos** [comment]
Yes, backward compatibility is a concern, and changing `test/test*.py` → `test*/**/*` feels better than removing default values. But then I agree, default values have their issues too: what happens, for example, in the case of a Python package named `testimony`?

Whatever changes here, the [Python Packaging User Guide](https://packaging.python.org/en/latest/guides/using-manifest-in/) should be updated at the same time:
> When building a [source distribution](https://packaging.python.org/en/latest/glossary/#term-Source-Distribution-or-sdist) for your package, by default only a minimal set of files are included. You may find yourself wanting to include extra files in the source distribution, such as [...] a directory of data files used for testing purposes.
> [...]
> The following files are included in a source distribution by default:
> * [...]
> * all files matching the pattern test/test*.py

**Comment by DimitriPapadopoulos** [comment]
> I do as a matter of course [exclude tests from packages to install](https://github.com/jaraco/skeleton/blob/9e13598ce4b81c2c964dd555fa407bb3ba4cc607/setup.cfg#L26).

Not that I necessarily disagree, but it is not a matter of course. The [Python Packaging User Guide](https://packaging.python.org/en/latest/guides/using-manifest-in/#how-files-are-included-in-an-sdist) currently implies that tests should **be included in source** distributions (see excerpts above), and the consensus seems to be that tests should **not be included in binary** distributions. Therefore:
- Could you point me to sources of information on consensus on the subject? That would be very helpful for confused end-users - like me.
- Should such a consensus be documented in the Python Packaging User Guide, as a suggestion more than a necessity?
- If the consensus is to include test in source distributions but not in binary distributions, how do I achieve that? I cannot find documentation on the subject.

**Comment by yukihiko-shinoda** [comment]
Shall we open this issue again? (or open another issue?)
I'm surprised that some of test files were suddenly included in sdist in last build. And it's not complete, followings are lacked:

- `conftest.py`
- Test libraries
- Test data

I thought that it must be bug.

The remains of issues are:

- Update [Python Packaging User Guide](https://packaging.python.org/en/latest/guides/using-manifest-in/#how-files-are-included-in-an-sdist)
- Include `test/*` and `tests/*` (not include other like `testimony`)
- Discuss whether test code really required or not in sdist
